package:
  name: spotlight
  version: "0.1.1"

source:
  git_url: https://github.com/maciejkula/spotlight.git
  git_rev: v0.1.1

build:
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - h5py
    - requests
    - pytorch 0.1.12

test:
  requires:
    - pytest

about:
  home: https://github.com/maciejkula/spotlight
  license: MIT
  license_file: LICENSE
