package:
  name: spotlight
  version: "0.1.0"

source:
  git_url: https://github.com/maciejkula/spotlight.git
  git_rev: 091264d59599ec59c2bee91cd6d4ee519bf28ea4 # v0.1.0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - h5py
    - requests
    - pytorch 0.1.12

about:
  home: https://github.com/maciejkula/spotlight
  license: MIT
  license_file: LICENSE
