matrix:
  include:
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.7
before_install:
  - ./.travis/install.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
install:
  - ./build.py
